import Head from 'next/head'
import Link from 'next/link'
import { Inter } from '@next/font/google'
import styles from '../styles/Home.module.css'
import { NextPage } from 'next'
import { useEffect, useState } from 'react'
import { Auth } from '../types/auth'
import Cookies from 'js-cookie';
import { useRouter } from 'next/router'
import {login} from '../lib/api/auth'

const inter = Inter({ subsets: ['latin'] })

const Home: NextPage = () => {

    const router = useRouter()

    const [email, setEmail] = useState('')
    const [password, setPassword] = useState('')
    const [data, setData] = useState([])

    const onClickLogin = async () => {
        if (!email && !password) {
            alert("Email and Password Required")
        } else {
            try {
                const request = await login({
                    body: {
                        email,
                        password,
                    }
                })
                const response: Auth = await request.json()
                if (request.status != 200) {
                    alert(response.error)
                } else {
                    Cookies.set("token", response.token)
                    router.push('/dashboard')
                }
                
            } catch (error) {
                console.log(error);
            }
        }
    }

    useEffect(() => {
        if (Cookies.get("token")) {
            router.push('/dashboard')
        }
    })

    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main className={'flex items-center justify-center h-screen'}>
                <div className='flex flex-col gap-5'>
                    <input type="text" className='border p-3' placeholder='Email' onChange={(e) => setEmail(e.target.value)} />
                    <input type="password" className='border p-3' placeholder='Password' onChange={(e) => setPassword(e.target.value)} />
                    <button onClick={onClickLogin} className='bg-white text-black py-2 px-5 rounded-lg'>Login</button>
                    <Link href={`/register`} className='hover:text-sky-500'>
                        Register Here
                    </Link>
                </div>
            </main>
        </>
    )
}

export default Home

