import { NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import { useRouter } from "next/router";
import { useEffect, useState } from "react";
import Cookies from 'js-cookie';
import { register } from "../lib/api/auth";
import { Auth } from "../types/auth";

const Register: NextPage = () => {

    const router = useRouter()

    const [firstName, setFirstName] = useState('')
    const [lastName, setLastName] = useState('')
    const [email, setEmail] = useState('')
    const [password, setPassword] = useState('')

    const onClickRegister = async () => {
        if (!firstName && !lastName && !email && !password) {
            alert("First Name, Last Name, Email and Password Required")
        } else {
            try {
                const request = await register({
                    body: {
                        email,
                        password,
                        first_name: firstName,
                        last_name: lastName,
                        gender: 'Male',
                    }
                })
                const response: Auth = await request.json()
                if (request.status != 200) {
                    alert(response.error)
                } else {
                    alert('Register Success. Back to login')
                    router.push('/')
                }
                
            } catch (error) {
                console.log(error);
            }
        }
    }

    useEffect(() => {
        if (Cookies.get("token")) {
            router.push('/dashboard')
        }
    })

    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main className={'flex items-center justify-center h-screen'}>
                <div className='flex flex-col gap-5'>
                    <input type="text" className='border p-3' placeholder='Nama Depan' onChange={(e) => setFirstName(e.target.value)} />
                    <input type="text" className='border p-3' placeholder='Nama Belakang' onChange={(e) => setLastName(e.target.value)} />
                    <input type="text" className='border p-3' placeholder='Email' onChange={(e) => setEmail(e.target.value)} />
                    <input type="password" className='border p-3' placeholder='Password' onChange={(e) => setPassword(e.target.value)} />
                    <button onClick={onClickRegister} className='bg-green-600 text-white py-2 px-5 rounded-lg'>Register</button>
                    <Link href={`/`} className='hover:text-sky-500'>
                        Login Here
                    </Link>
                </div>
            </main>
        </>
    )
}

export default Register